name: flutter_encryption
description: A sample command-line application with basic argument parsing.
version: 0.0.1
#repository: https://github.com/chanbinme/flutter-encryption

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  args: ^2.5.0
  encrypt: ^5.0.3
  rsa_encrypt: ^2.0.0
  pointycastle: ^3.1.1
  asn1lib: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter